name: Frontend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run Production Build
        run: npm run build
        env:
          NEXT_PUBLIC_API_BASE_URL: https://api.redlinekomputer.my.id/api/v1
          NEXT_PUBLIC_WA_PHONE: 6285640203069
